# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algotrader/model/series_bundle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algotrader/model/series_bundle.proto',
  package='algotrader.model2',
  syntax='proto3',
  serialized_pb=_b('\n$algotrader/model/series_bundle.proto\x12\x11\x61lgotrader.model2\"\xd9\x01\n\x0cSeriesBundle\x12\r\n\x05\x64\x66_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0f\n\x07inst_id\x18\x03 \x01(\t\x12\x16\n\x0eseries_id_list\x18\n \x03(\t\x12I\n\x0eparent_and_cls\x18\x0b \x03(\x0b\x32\x31.algotrader.model2.SeriesBundle.ParentAndClsEntry\x1a\x33\n\x11ParentAndClsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_SERIESBUNDLE_PARENTANDCLSENTRY = _descriptor.Descriptor(
  name='ParentAndClsEntry',
  full_name='algotrader.model2.SeriesBundle.ParentAndClsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='algotrader.model2.SeriesBundle.ParentAndClsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='algotrader.model2.SeriesBundle.ParentAndClsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=277,
)

_SERIESBUNDLE = _descriptor.Descriptor(
  name='SeriesBundle',
  full_name='algotrader.model2.SeriesBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='df_id', full_name='algotrader.model2.SeriesBundle.df_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='algotrader.model2.SeriesBundle.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inst_id', full_name='algotrader.model2.SeriesBundle.inst_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='series_id_list', full_name='algotrader.model2.SeriesBundle.series_id_list', index=3,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_and_cls', full_name='algotrader.model2.SeriesBundle.parent_and_cls', index=4,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SERIESBUNDLE_PARENTANDCLSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=277,
)

_SERIESBUNDLE_PARENTANDCLSENTRY.containing_type = _SERIESBUNDLE
_SERIESBUNDLE.fields_by_name['parent_and_cls'].message_type = _SERIESBUNDLE_PARENTANDCLSENTRY
DESCRIPTOR.message_types_by_name['SeriesBundle'] = _SERIESBUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeriesBundle = _reflection.GeneratedProtocolMessageType('SeriesBundle', (_message.Message,), dict(

  ParentAndClsEntry = _reflection.GeneratedProtocolMessageType('ParentAndClsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERIESBUNDLE_PARENTANDCLSENTRY,
    __module__ = 'algotrader.model.series_bundle_pb2'
    # @@protoc_insertion_point(class_scope:algotrader.model2.SeriesBundle.ParentAndClsEntry)
    ))
  ,
  DESCRIPTOR = _SERIESBUNDLE,
  __module__ = 'algotrader.model.series_bundle_pb2'
  # @@protoc_insertion_point(class_scope:algotrader.model2.SeriesBundle)
  ))
_sym_db.RegisterMessage(SeriesBundle)
_sym_db.RegisterMessage(SeriesBundle.ParentAndClsEntry)


_SERIESBUNDLE_PARENTANDCLSENTRY.has_options = True
_SERIESBUNDLE_PARENTANDCLSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
