# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algotrader/model/time_series2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algotrader/model/time_series2.proto',
  package='algotrader.model2',
  syntax='proto3',
  serialized_pb=_b('\n#algotrader/model/time_series2.proto\x12\x11\x61lgotrader.model2\"\xa6\x02\n\x06Series\x12\x11\n\tseries_id\x18\x01 \x01(\t\x12\r\n\x05\x64\x66_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63ol_id\x18\x03 \x01(\t\x12\x0f\n\x07inst_id\x18\x04 \x01(\t\x12\x11\n\tsource_id\x18\x05 \x01(\t\x12*\n\x05\x64type\x18\x06 \x01(\x0e\x32\x1b.algotrader.model2.DataType\x12\r\n\x05index\x18\x0b \x03(\x03\x12\x12\n\nfloat_data\x18\x14 \x03(\x02\x12\x13\n\x0b\x64ouble_data\x18\x15 \x03(\x01\x12\x12\n\nint32_data\x18\x16 \x03(\x05\x12\x12\n\nint64_data\x18\x17 \x03(\x03\x12\x11\n\tbool_data\x18\x18 \x03(\x08\x12\x13\n\x0bstring_data\x18\x19 \x03(\t\x12\x12\n\nbytes_data\x18\x1a \x03(\x0c\"\x8b\x01\n\x0eTimeSeriesItem\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x39\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32+.algotrader.model2.TimeSeriesItem.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"X\n\x15TimeSeriesUpdateEvent\x12\x0e\n\x06source\x18\x01 \x01(\t\x12/\n\x04item\x18\x02 \x01(\x0b\x32!.algotrader.model2.TimeSeriesItem*j\n\x08\x44\x61taType\x12\x0b\n\x07\x44TFloat\x10\x00\x12\x0c\n\x08\x44TDouble\x10\x01\x12\x0b\n\x07\x44TInt32\x10\x02\x12\x0b\n\x07\x44TInt64\x10\x03\x12\n\n\x06\x44TBool\x10\x04\x12\x0c\n\x08\x44TString\x10\x05\x12\x0f\n\x0b\x44TByteArray\x10\x06\x62\x06proto3')
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='algotrader.model2.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DTFloat', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTDouble', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTInt32', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTInt64', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTBool', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTString', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTByteArray', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=587,
  serialized_end=693,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
DTFloat = 0
DTDouble = 1
DTInt32 = 2
DTInt64 = 3
DTBool = 4
DTString = 5
DTByteArray = 6



_SERIES = _descriptor.Descriptor(
  name='Series',
  full_name='algotrader.model2.Series',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='series_id', full_name='algotrader.model2.Series.series_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='df_id', full_name='algotrader.model2.Series.df_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='col_id', full_name='algotrader.model2.Series.col_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inst_id', full_name='algotrader.model2.Series.inst_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='algotrader.model2.Series.source_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='algotrader.model2.Series.dtype', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='algotrader.model2.Series.index', index=6,
      number=11, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='algotrader.model2.Series.float_data', index=7,
      number=20, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_data', full_name='algotrader.model2.Series.double_data', index=8,
      number=21, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int32_data', full_name='algotrader.model2.Series.int32_data', index=9,
      number=22, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int64_data', full_name='algotrader.model2.Series.int64_data', index=10,
      number=23, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_data', full_name='algotrader.model2.Series.bool_data', index=11,
      number=24, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='algotrader.model2.Series.string_data', index=12,
      number=25, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_data', full_name='algotrader.model2.Series.bytes_data', index=13,
      number=26, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=353,
)


_TIMESERIESITEM_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='algotrader.model2.TimeSeriesItem.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='algotrader.model2.TimeSeriesItem.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='algotrader.model2.TimeSeriesItem.DataEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=495,
)

_TIMESERIESITEM = _descriptor.Descriptor(
  name='TimeSeriesItem',
  full_name='algotrader.model2.TimeSeriesItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='algotrader.model2.TimeSeriesItem.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='algotrader.model2.TimeSeriesItem.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TIMESERIESITEM_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=495,
)


_TIMESERIESUPDATEEVENT = _descriptor.Descriptor(
  name='TimeSeriesUpdateEvent',
  full_name='algotrader.model2.TimeSeriesUpdateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='algotrader.model2.TimeSeriesUpdateEvent.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='algotrader.model2.TimeSeriesUpdateEvent.item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=585,
)

_SERIES.fields_by_name['dtype'].enum_type = _DATATYPE
_TIMESERIESITEM_DATAENTRY.containing_type = _TIMESERIESITEM
_TIMESERIESITEM.fields_by_name['data'].message_type = _TIMESERIESITEM_DATAENTRY
_TIMESERIESUPDATEEVENT.fields_by_name['item'].message_type = _TIMESERIESITEM
DESCRIPTOR.message_types_by_name['Series'] = _SERIES
DESCRIPTOR.message_types_by_name['TimeSeriesItem'] = _TIMESERIESITEM
DESCRIPTOR.message_types_by_name['TimeSeriesUpdateEvent'] = _TIMESERIESUPDATEEVENT
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Series = _reflection.GeneratedProtocolMessageType('Series', (_message.Message,), dict(
  DESCRIPTOR = _SERIES,
  __module__ = 'algotrader.model.time_series2_pb2'
  # @@protoc_insertion_point(class_scope:algotrader.model2.Series)
  ))
_sym_db.RegisterMessage(Series)

TimeSeriesItem = _reflection.GeneratedProtocolMessageType('TimeSeriesItem', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _TIMESERIESITEM_DATAENTRY,
    __module__ = 'algotrader.model.time_series2_pb2'
    # @@protoc_insertion_point(class_scope:algotrader.model2.TimeSeriesItem.DataEntry)
    ))
  ,
  DESCRIPTOR = _TIMESERIESITEM,
  __module__ = 'algotrader.model.time_series2_pb2'
  # @@protoc_insertion_point(class_scope:algotrader.model2.TimeSeriesItem)
  ))
_sym_db.RegisterMessage(TimeSeriesItem)
_sym_db.RegisterMessage(TimeSeriesItem.DataEntry)

TimeSeriesUpdateEvent = _reflection.GeneratedProtocolMessageType('TimeSeriesUpdateEvent', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIESUPDATEEVENT,
  __module__ = 'algotrader.model.time_series2_pb2'
  # @@protoc_insertion_point(class_scope:algotrader.model2.TimeSeriesUpdateEvent)
  ))
_sym_db.RegisterMessage(TimeSeriesUpdateEvent)


_TIMESERIESITEM_DATAENTRY.has_options = True
_TIMESERIESITEM_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
